[package]
name = "tinymazers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[dependencies.elefren]
git = "https://github.com/DeeUnderscore/elefren.git"
features = ["toml"]
